module.exports = {
  parserOptions: {
    ecmaVersion: 9,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:jsx-a11y/strict',
  ],
  rules: {
    'react/boolean-prop-naming': 2,
    'react/no-array-index-key': 2,
    'react/no-set-state': 2,
    'react/no-typos': 2,
    'react/no-this-in-sfc': 2,
    'react/no-unsafe': 2,
    'react/no-unused-prop-types': 2,
    'react/no-unused-state': 2,
    'react/prefer-stateless-function': 1,
    'react/require-default-props': 2,
    'react/self-closing-comp': 2,
    'react/sort-prop-types': 1,
    'react/style-prop-object': 2,
    'react/void-dom-elements-no-children': 2,
    'react/jsx-boolean-value': 2,
    'react/jsx-closing-bracket-location': 2,
    'react/jsx-closing-tag-location': 2,
    'react/jsx-filename-extension': [1, { extensions: ['.js'] }],
    'react/jsx-first-prop-new-line': 'multiline-multiprop',
    'react/jsx-handler-names': 2,
    'react/jsx-no-bind': 2,
    'react/jsx-one-expression-per-line': [2, { allow: 'single-child' }],
    'react/jsx-fragments': 2,
    'react/jsx-pascal-case': 2,
    'react/jsx-props-no-multi-spaces': 2,
    'react/jsx-sort-default-props': 2,
    'react/jsx-sort-props': 2,
    'react/react-in-jsx-scope': 0,
  },
  settings: {
    react: {
      version: 'detect',
    },
    linkComponents: [{ name: 'Link', linkAttribute: 'to' }],
  },
};
